# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ ci/enableCIaction ]
  pull_request:
    branches: [ ci/enableCIaction ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kas
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pwd
        ls
    - name: Build Example Image
      run: |
        kas build meta-iot2000/kas-example.yml

    - name: Build BSP Image
      run: |
        kas build meta-iot2000/kas-bsp.yml

    - name: Build BSP Image
      run: |
        kas build meta-iot2000/kas-sdk-windows-i586.yml

    - name: Build BSP Image
      run: |
        kas build meta-iot2000/kas-sdk-linux-x64.yml
